<?php
defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Script generated by taiscript
 */

class Homecontroller extends CI_Controller
{
    public function index()
    {
        //code
    }
}